config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_bash_it:
    dst: ~/.bash_it
    src: bash_it
  d_oh-my-zsh:
    dst: ~/.oh-my-zsh
    src: oh-my-zsh
  d_tmux:
    dst: ~/.tmux
    src: tmux
  f_bashrc:
    dst: ~/.bashrc
    src: bashrc
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    src: config/nvim/init.vim
  f_kitty.conf:
    dst: ~/.config/kitty/kitty.conf
    src: config/kitty/kitty.conf
  f_plug.vim:
    dst: ~/.local/share/nvim/site/autoload/plug.vim
    src: local/share/nvim/site/autoload/plug.vim
  f_profile:
    dst: ~/.profile
    src: profile
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  base:
    dotfiles:
    - f_init.vim
    - f_tmux.conf
    - f_bashrc
    - d_bash_it
    - f_profile
    - d_tmux
    - f_plug.vim
    - f_gitconfig
    - d_oh-my-zsh
    - f_zshrc
    - f_kitty.conf
  work:
    dotfiles:
    - f_init.vim
    - f_tmux.conf
    - f_bashrc
    - d_bash_it
    - f_profile
    - d_tmux
    - f_plug.vim
    - f_gitconfig
    - d_oh-my-zsh
    - f_zshrc
    - f_kitty.conf
